### ISSUE TITLE
ISSUE: The Rebase Actually Happened

### ISSUE THREAD

**Issue by Nickvr628** [yogstation13/tg-rebase#564]
It fucking sucks. It lags to hell, movement is buggy, none of our players are robust enough for the SM, and anytime we try to do a round, nich force-nukes the station 15 minutes in (see the round a few minutes ago). Why did we want this to happen?

Unbase when.

**Comment by nichlas0010** [comment]
go die you fucking cunt

**Comment by kooarbiter** [comment]
nich please, this rebase is cancer, make it stop

**Comment by ThatLing** [comment]
#rebase-discussion has been up for months but all you've done is meme in it :)
